### ISSUE TITLE
Overflow issues on desktop sizing

### ISSUE THREAD

**Issue by MBJean** [dhmit/dhmit-site-2020#62]
Several pages throughout the preview website seem to overflow the browser window width (see images below). This does not make the layout appear visually incorrect, but it does produce an unnecessary horizontal scrollbar. These pages include:

`/projects/*/`, if populated
`/person/*/`, if in two-column layout
`/event/*/`, if in two-column layout
`/posts/*/`, if in two-column layout

![Screen Shot 2021-06-08 at 9 57 21 AM](https://user-images.githubusercontent.com/20114078/121198313-09a1e880-c840-11eb-882a-e611dab6e1f0.png)

![Screen Shot 2021-06-08 at 9 57 43 AM](https://user-images.githubusercontent.com/20114078/121198326-0b6bac00-c840-11eb-978a-1c26558a6754.png)

**Comment by ryaanahmed** [comment]
Same issue also appears on those pages on mobile. See here, e.g., the bottom right corner of `/projects/faculty-fellowships/`. Note there is a layout issue as well: the footer doesn't cover the full container width.

![unnamed](https://user-images.githubusercontent.com/691117/121199666-1e32b080-c841-11eb-9725-9014362938df.png)
