### ISSUE TITLE
Projects - add faculty metadata on detail pages and cards

### ISSUE THREAD

**Issue by ryaanahmed** [dhmit/dhmit-site-2020#63]
In latest Figma mockups, project detail pages included a “Led by” subhead, which is missing in the implementation. Not sure if it’s just missing metadata in the CMS or actually not displayed in the site.

Is it possible to add this metadata to the project cards as well, both on the landing page and projects page?

**Comment by mikehwagz** [comment]
@ryaanahmed there is currently a subtitle field that is used for both the cards and the detail page. I see 2 potential options here:

1. Update subtitle field to include the "Led by" info
2. Have 1 subtitle field control the card subtitle and another field control the detail page subtitle

What do you think?

**Comment by ryaanahmed** [comment]
Let's keep it simple and have a single field for now. We can always add another later if need be!

**Comment by ryaanahmed** [comment]
Wait I take it back—Sophie suggests two fields will be better for her use (and I defer to that!). Let's do two, please.

**Comment by mikehwagz** [comment]
Sounds good!
